### ISSUE TITLE
Getting neighbors for encode_uint64

### ISSUE THREAD

**Issue by winash12** [hkwi/python-geohash#26]
I think we need an extra method when you encode with encode_uint64 for getting neighbors. Right now it will only with character geohash.

This is the error I am getting -  

```
Traceback (most recent call last):
  File "test4.py", line 123, in <module>
    main()
  File "test4.py", line 30, in main
    neighbors = gh.neighbors(ghash)
  File "/usr/local/lib/python3.6/dist-packages/python_geohash-0.8.5-py3.6-linux-x86_64.egg/geohash.py", line 239, in neighbors
    if _geohash and len(hashcode)<25:
TypeError: object of type 'int' has no len()
```

**Comment by winash12** [comment]
Instead of doing len(hashcode) what I think you can do is hascode.bit_length() which is available with python 3.x onwards.

**Comment by winash12** [comment]
Any updates on this issue ?
